### ISSUE TITLE
Start server option crash_expected breaks test-run

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/test-run#109]
Here's a minimal reproduce
Let's say we have a test `replication/asdf.test.lua`:
```
test_run = require('test_run').new()
test_run:cmd('create server failure with script="replication/failure.lua"')
test_run:cmd('start server failure')
require('fiber').sleep(0.5)
test_run:cmd('cleanup server failure')
```
with instance file for `failure` `replication/failure.lua`:
```
box.cfg{}
os.exit(1)
```
Now running `./test-run.py replication/asdf replication/autobootstrap --force'` will show such output:
```
[001] replication/asdf.test.lua                       memtx           [ pass ]
[001] replication/asdf.test.lua                       vinyl           [ fail ]
[001] 
[001] Test failed! Result content mismatch:
[001] --- replication/asdf.result	Wed Aug  8 17:48:55 2018
[001] +++ replication/asdf.reject	Wed Aug  8 17:50:44 2018
[001] @@ -1,18 +1,7 @@
[001]  test_run = require('test_run').new()
[001] ----
[001] -...
[001]  test_run:cmd('create server failure with script="replication/failure.lua"')
[001] ----
[001] -- true
[001] -...
[001] +[Lost current connection]
[001]  test_run:cmd('start server failure with crash_expected=True')
[001] ----
[001] -- false
[001] -...
[001]  require('fiber').sleep(0.1)
[001] ----
[001] -...
[001] +[Lost current connection]
[001]  test_run:cmd('cleanup server failure')
[001] ----
[001] -- true
[001] -...
[001] 
[001] Last 15 lines of Tarantool Log file [Instance "master"][/Users/s.petrenko/Source/tarantool/test/var/001_replication/master.log]:
[001] started
[001] mkdir /Users/s.petrenko/Source/tarantool/test/var/001_replication/master
[001] 2018-08-08 17:50:44.501 [7319] main/101/master C> Tarantool 1.10.1-251-gce2684c85
[001] 2018-08-08 17:50:44.502 [7319] main/101/master C> log level 5
[001] 2018-08-08 17:50:44.502 [7319] main/101/master I> mapping 117440512 bytes for memtx tuple arena...
[001] 2018-08-08 17:50:44.502 [7319] main/101/master I> mapping 134217728 bytes for vinyl tuple arena...
[001] 2018-08-08 17:50:44.509 [7319] iproto/101/main I> binary: bound to [::1]:38199
[001] 2018-08-08 17:50:44.509 [7319] main/101/master I> initializing an empty data directory
[001] 2018-08-08 17:50:44.531 [7319] snapshot/101/main I> saving snapshot `/Users/s.petrenko/Source/tarantool/test/var/001_replication/master/00000000000000000000.snap.inprogress'
[001] 2018-08-08 17:50:44.538 [7319] snapshot/101/main I> done
[001] 2018-08-08 17:50:44.538 [7319] main/101/master I> ready to accept requests
[001] 2018-08-08 17:50:44.539 [7319] main/108/checkpoint_daemon I> started
[001] 2018-08-08 17:50:44.539 [7319] main/108/checkpoint_daemon I> scheduled the next snapshot at Wed Aug  8 19:46:32 2018
[001] 2018-08-08 17:50:44.542 [7319] main/113/console/::1:38598 I> started
[001] 2018-08-08 17:50:44.542 [7319] main C> entering the event loop
No output during 10 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 20 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 30 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 40 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 50 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 60 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 70 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 80 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 90 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 100 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 110 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.
No output during 120 seconds. List of workers not reporting the status: [1]; Will abort after 120 seconds without output.

[Main process] No output from workers. It seems that we hang. Send SIGKILL to workers; exiting...
---------------------------------------------------------------------------------
Statistics:
* fail: 1
* pass: 1
Failed tasks:
- [replication/asdf.test.lua, vinyl]
# logfile:        /Users/s.petrenko/Source/tarantool/test/var/log/001_replication.log
# reproduce file: /Users/s.petrenko/Source/tarantool/test/var/reproduce/001_replication.list.yaml
The following tasks were dispatched on some worker task queue, but were not reported as done (does not matters success or fail):
- [replication/autobootstrap.test.lua, memtx]
- [replication/autobootstrap.test.lua, vinyl]
- [replication/autobootstrap_guest.test.lua, memtx]
- [replication/autobootstrap_guest.test.lua, vinyl]

```
The same applies to running any of our normal replication tests after this example.
If I add `test_run:cmd('stop server failure')` (which is unneeded, since `failure` exits), it just adds another error to the output but still hangs:
```
[001] replication/asdf.test.lua                       memtx           
[001] TarantoolInpector.handle() received the following error:
[001] Traceback (most recent call last):
[001]   File "/Users/s.petrenko/Source/tarantool/test-run/lib/inspector.py", line 92, in handle
[001]     result = self.parser.parse_preprocessor(line)
[001]   File "/Users/s.petrenko/Source/tarantool/test-run/lib/preprocessor.py", line 95, in parse_preprocessor
[001]     return self.server(stype, sname, options)
[001]   File "/Users/s.petrenko/Source/tarantool/test-run/lib/preprocessor.py", line 295, in server
[001]     return getattr(self, attr)(ctype, sname, opts)
[001]   File "/Users/s.petrenko/Source/tarantool/test-run/lib/preprocessor.py", line 192, in server_stop
[001]     self.connections[sname].disconnect()
[001] KeyError: 'failure'
[001] 
[001] [ pass ]

```

**Comment by sergw** [comment]
It seems this bug not in test-run:

## running Master
```
$ ~/build/src/tarantool master.lua
2018-08-15 11:32:01.141 [3729] main/101/master.lua C> Tarantool 2.0.4-828-ge28ce80ad
2018-08-15 11:32:01.141 [3729] main/101/master.lua C> log level 5
2018-08-15 11:32:01.142 [3729] main/101/master.lua I> mapping 268435456 bytes for memtx tuple arena...
2018-08-15 11:32:01.142 [3729] main/101/master.lua I> mapping 134217728 bytes for vinyl tuple arena...
2018-08-15 11:32:01.149 [3729] iproto/101/main I> binary: bound to [::]:33011
2018-08-15 11:32:01.151 [3729] main/106/applier/replicator@127.0.0.1:33 I> can't connect to master
2018-08-15 11:32:01.151 [3729] main/106/applier/replicator@127.0.0.1:33 coio.cc:106 !> SystemError connect, called on fd 14, aka 127.0.0.1:51030: Connection refused
2018-08-15 11:32:01.151 [3729] main/106/applier/replicator@127.0.0.1:33 I> will retry every 1.00 second
2018-08-15 11:32:01.151 [3729] main/105/applier/replicator@127.0.0.1:33 I> remote master is 2.0.4 at 127.0.0.1:33011
```

## running Replica with os.exit(1)
```
$ ~/build/src/tarantool failure.lua
2018-08-15 11:33:42.681 [3730] main/101/failure.lua C> Tarantool 2.0.4-828-ge28ce80ad
2018-08-15 11:33:42.681 [3730] main/101/failure.lua C> log level 5
2018-08-15 11:33:42.681 [3730] main/101/failure.lua I> mapping 268435456 bytes for memtx tuple arena...
2018-08-15 11:33:42.682 [3730] main/101/failure.lua I> mapping 134217728 bytes for vinyl tuple arena...
2018-08-15 11:33:42.690 [3730] iproto/101/main I> binary: bound to [::]:33012
2018-08-15 11:33:42.692 [3730] main/105/applier/replicator@127.0.0.1:33 I> remote master is 2.0.4 at 127.0.0.1:33011
2018-08-15 11:33:42.692 [3730] main/106/applier/replicator@127.0.0.1:33 I> remote master is 2.0.4 at 127.0.0.1:33012
2018-08-15 11:33:42.693 [3730] main/105/applier/replicator@127.0.0.1:33 I> failed to authenticate
2018-08-15 11:33:42.693 [3730] main/105/applier/replicator@127.0.0.1:33 xrow.c:945 E> ER_LOADING: Instance bootstrap hasn't finished yet
2018-08-15 11:33:43.696 [3730] main/105/applier/replicator@127.0.0.1:33 I> authenticated
2018-08-15 11:33:43.697 [3730] main/101/failure.lua I> bootstrapping replica from 8d83b995-7b16-4157-8efc-7df26baf9067 at 127.0.0.1:33011
2018-08-15 11:33:43.721 [3730] main/105/applier/replicator@127.0.0.1:33 I> initial data received
2018-08-15 11:33:43.722 [3730] main/105/applier/replicator@127.0.0.1:33 I> final data received
2018-08-15 11:33:43.744 [3730] snapshot/101/main I> saving snapshot `./00000000000000000008.snap.inprogress'
2018-08-15 11:33:43.746 [3730] snapshot/101/main I> done
2018-08-15 11:33:43.748 [3730] main/105/applier/replicator@127.0.0.1:33 C> leaving orphan mode
2018-08-15 11:33:43.748 [3730] main/101/failure.lua C> replica set sync complete, quorum of 2 replicas formed
2018-08-15 11:33:43.748 [3730] main/101/failure.lua I> ready to accept requests
2018-08-15 11:33:43.749 [3730] main/110/checkpoint_daemon I> started
2018-08-15 11:33:43.749 [3730] main/110/checkpoint_daemon I> scheduled the next snapshot at Wed Aug 15 12:45:53 2018
2018-08-15 11:33:43.749 [3730] main/101/failure.lua I> set 'read_only' configuration option to true
$ echo $?
1
```

## from Master logs
```
2018-08-15 11:33:43.408 [3729] main/106/applier/replicator@127.0.0.1:33 I> remote master is 2.0.4 at 127.0.0.1:33012
2018-08-15 11:33:43.408 [3729] main/101/master.lua I> initializing an empty data directory
2018-08-15 11:33:43.434 [3729] main/101/master.lua xlog.c:1850 E> can't open tx: bootstrap: has some data after eof marker at 1813
2018-08-15 11:33:43.437 [3729] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2018-08-15 11:33:43.454 [3729] snapshot/101/main I> done
2018-08-15 11:33:43.455 [3729] main/101/master.lua I> ready to accept requests
2018-08-15 11:33:43.456 [3729] main/110/checkpoint_daemon I> started
2018-08-15 11:33:43.456 [3729] main/110/checkpoint_daemon I> scheduled the next snapshot at Wed Aug 15 12:41:57 2018
2018-08-15 11:33:43.456 [3729] main/106/applier/replicator@127.0.0.1:33 I> failed to authenticate
2018-08-15 11:33:43.456 [3729] main/106/applier/replicator@127.0.0.1:33 xrow.c:945 E> ER_LOADING: Instance bootstrap hasn't finished yet
box.once executed on master
2018-08-15 11:33:43.458 [3729] main C> entering the event loop
2018-08-15 11:33:43.700 [3729] main/107/main I> initial data sent.
2018-08-15 11:33:43.700 [3729] relay/[::ffff:127.0.0.1]:51139/101/main I> recover from `./00000000000000000000.xlog'
2018-08-15 11:33:43.701 [3729] main/107/main I> final data sent.
2018-08-15 11:33:43.748 [3729] relay_0x7fecae015800/101/main I> recover from `./00000000000000000000.xlog'
2018-08-15 11:33:43.748 [3729] relay_0x7fecae015800/101/main I> done `./00000000000000000000.xlog'
2018-08-15 11:33:43.756 [3729] relay/[::ffff:127.0.0.1]:51139/101/main C> exiting the relay loop
2018-08-15 11:33:43.756 [3729] main/107/main coio.cc:370 !> SystemError unexpected EOF when reading from socket, called on fd 14, aka [::ffff:127.0.0.1]:33011, peer of [::ffff:127.0.0.1]: Broken pipe
2018-08-15 11:33:44.458 [3729] main/106/applier/replicator@127.0.0.1:33 I> can't connect to master
2018-08-15 11:33:44.458 [3729] main/106/applier/replicator@127.0.0.1:33 coio.cc:106 !> SystemError connect, called on fd 13, aka 127.0.0.1:51140: Connection refused
2018-08-15 11:33:44.458 [3729] main/106/applier/replicator@127.0.0.1:33 I> will retry every 1.00 second
Assertion failed: (0), function replica_on_applier_disconnect, file /Users/s.voronezhskii/tarantool/src/box/replication.cc, line 356.
Abort trap: 6
$ echo $?
134
```


## master.lua
```lua
#!/usr/bin/env tarantool
box.cfg({
    listen              = 33011,
    replication = {'replicator:password@127.0.0.1:33011',  -- master URI
                   'replicator:password@127.0.0.1:33012'}, -- replica URI
    read_only           = false,
    work_dir            = './master',
})

box.once("schema", function()
   box.schema.user.create('replicator', {password = 'password'})
   box.schema.user.grant('replicator', 'replication') -- grant replication role
   box.schema.space.create("test")
   box.space.test:create_index("primary")
   print('box.once executed on master')
end)
```

## failure.lua
```lua
#!/usr/bin/env tarantool
box.cfg({
    listen              = 33012,
    replication = {'replicator:password@127.0.0.1:33011',  -- master URI
                   'replicator:password@127.0.0.1:33012'}, -- replica URI
    read_only           = true,
    work_dir            = './failure',
})

os.exit(1) -- if drop this line, master and replica works properly

box.once("schema", function()
   box.schema.user.create('replicator', {password = 'password'})
   box.schema.user.grant('replicator', 'replication') -- grant replication role
   box.schema.space.create("test")
   box.space.test:create_index("primary")
   print('box.once executed on replica')
end)
```

Code for master <-> replica taken from docs: https://tarantool.io/en/doc/1.9/book/replication/repl_bootstrap/

**Comment by sergepetrenko** [comment]
@sergw 
The error you mention
`Assertion failed: (0), function replica_on_applier_disconnect, file /Users/s.voronezhskii/tarantool/src/box/replication.cc, line 356.
Abort trap: 6`
Is fixed in scope of the patch I ran the tests for and still got the problem. (tarantool/tarantool#3510)

Also, when running tests, we have such master configuration: `/test/replication/master.lua`
```
#!/usr/bin/env tarantool
os = require('os')
box.cfg({
    listen              = os.getenv("LISTEN"),
    memtx_memory        = 107374182,
    replication_connect_timeout = 0.5,
})

require('console').listen(os.getenv('ADMIN'))
```
As you can see, no replication is set here, so such error isn't possible.
In my example above, also no replication is configured, and master reports no errors. So this is a test-run problem or some other yet uncovered problem in server.
