### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/test-run#24]
mock build on fedora-rawhide arm:
```
engine/recover_snapshot.test.lua                sophia          Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/builddir/build/BUILD/tarantool-1.6.8.496/test-run/lib/tarantool_server.py", line 75, in exec_loop
    sys.stdout.write(result.replace("\r\n", "\n"))
AttributeError: 'NoneType' object has no attribute 'replace'
<Greenlet at 0xb53e8170L: <bound method LuaTest.exec_loop of <lib.tarantool_server.LuaTest instance at 0xb5ec1d50>>(<lib.preprocessor.TestState object at 0xb5d732f0>)> failed with AttributeError
[ fail ]
Test failed! Result content mismatch:
--- engine/recover_snapshot.result      Tue Feb 16 08:20:00 2016
+++ engine/recover_snapshot.reject      Tue Feb 16 18:52:51 2016
@@ -37,377 +37,4 @@
 ---
 ...
 box.snapshot()
----
-- ok
-...
 test_run:cmd('restart server default')
-name = string.match(arg[0], "([^,]+)%.lua")
```

**Comment by Sulverus** [comment]
Reproduced 2 cases:
* there is no connection with tarantool instance
* tarantool crashed

We need to detect craches and write to result file:
```
-- some lua operations
[instance <app_name> crashed]
----------------------------------------------
backtrace from instance log
----------------------------------------------
-- some lua operations
```
This information can help with debugging tarantool
N.B> in some tests we need to crash tarantool, so crashed instance != failed test

**Comment by rtsisyk** [comment]
> tarantool crashed
Yeah, you are right.
It would be nice to see Tarantool log.


One more case:
```
box/tree_pk_multipart.test.lua                                  [ pass ]
box/tree_variants.test.lua                                      [ pass ]
box/tuple.test.lua                                              Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/builddir/build/BUILD/tarantool-1.6.8.525/test-run/lib/tarantool_server.py", line 75, in exec_loop
    sys.stdout.write(result.replace("\r\n", "\n"))
AttributeError: 'NoneType' object has no attribute 'replace'
<Greenlet at 0xf5dffcacL: <bound method LuaTest.exec_loop of <lib.tarantool_server.LuaTest instance at 0xf69022ec>>(<lib.preprocessor.TestState object at 0xf5df6dcc>)> failed with AttributeError
[ fail ]
Test failed! Result content mismatch:
--- box/tuple.result	Wed Feb 24 09:39:14 2016
+++ box/tuple.reject	Thu Feb 25 19:22:55 2016
@@ -955,14 +955,4 @@
 -- lbox_tuple_new() didn't check result of box_tuple_new() for NULL
 -- try to allocate 1GB tuple and checked that server won't crash
 box.tuple.new(string.rep('x', 1024 * 1024 * 1024)) == nil
----
-- error: not enough memory
-...
 collectgarbage('collect') -- collect huge string
----
-- 0
-...
-test_run:cmd("clear filter")
----
-- true
-...
Last 15 lines of Tarantool Log file:
Fatal error: Failed to run test box/tuple.test.lua: wrong test output. Execution aborted.
[INFO/MainProcess] process shutting down
error: Bad exit status from /var/tmp/rpm-tmp.iLar3e (%check)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.iLar3e (%check)
```

**Comment by Sulverus** [comment]
Implemented in gh-19
1. Lost connection case
2. Crash
output example
```
@@ -1023,3 +1023,7 @@
 ---
 - true
 ...
+ffi = require('ffi')
+---
+...
+ffi.cast('int*',0)[1]=42
+[Instance "box" crash detected]
+[Signal=6]
+#0  0x4281af in ?
+#1  0x7f86d3793340 in ?
+#2  0x532668 in ?
+#3  0x52eefd in ?
+#4  0x53c5e1 in ?
+#5  0x543a3b in ?
```

**Comment by Sulverus** [comment]
Merged
