### ISSUE TITLE
OSError on process.terminate on hard loaded hosts

### ISSUE THREAD

**Issue by avtikhon** [tarantool/test-run#270]
Reproduce on dev1 host in debian-stretch docker image:
1. run heavy test processes:
```
rm -rf atop_all.log ; ( atop -a -R -w atop_all.log 10000 & echo $! >atop.pid & ) ; ( export PATH=$PATH:/tnt/src ; export REPLICATION_SYNC_TIMEOUT=500 ; export TEST_TIMEOUT=510 ; export NO_OUTPUT_TIMEOUT=520 ; date ; time ./test-run.py -j 1200 --builddir /tnt --vardir var_hdd_vinyl `for r in {1..200} ; do echo vinyl/gh-5141-invalid-vylog-file ; done` --force 2>&1 ; sleep 1 ; kill -USR2 `cat atop.pid` ; date ) > test_atop.log &
```
2. run test which will be terminated on timeout and the issue will appear:
```
( export PATH=$PATH:/tnt/src; export REPLICATION_SYNC_TIMEOUT=100; export TEST_TIMEOUT=110; export NO_OUTPUT_TIMEOUT=120; time ./test-run.py sql-tap/index4.test.lua --buildd
ir /tnt --vardir var_hdd_test --conf vinyl ) > a.log 2>&1
``` 
Issue:
```
No output during 10 seconds. Will abort after 120 seconds without output. List of workers not reporting the status:
- 001_sql-tap [sql-tap/index4.test.lua, vinyl] at var_hdd_test/001_sql-tap/index4.result:0
[001] sql-tap/index4.test.lua                         vinyl           Test timeout of 110 secs reached  [ fail ]
[001] Test failed! Output from reject file var_hdd_test/rejects/sql-tap/index4.reject:
[001]
[001] Last 15 lines of Tarantool Log file [Instance "app_server"][/source/test/var_hdd_test/001_sql-tap/index4.test.lua:vinyl.tarantool.log]:
[Main process] Got failed test; gently terminate all workers...
Traceback (most recent call last):
  File "./test-run.py", line 230, in <module>
    status = main_parallel()
  File "./test-run.py", line 145, in main_parallel
    res = main_loop_parallel()
  File "./test-run.py", line 117, in main_loop_parallel
    dispatcher.wait()   
  File "/source/test-run/dispatcher.py", line 278, in wait
    objs = self.invoke_listeners(inputs, ready_inputs)
  File "/source/test-run/dispatcher.py", line 309, in invoke_listeners
    listener.process_result(obj)
  File "/source/test-run/listeners.py", line 241, in process_result
    self.terminate_all_workers()
  File "/source/test-run/dispatcher.py", line 115, in terminate_all_workers
    process.terminate() 
  File "/usr/lib/python2.7/multiprocessing/process.py", line 137, in terminate
    self._popen.terminate()
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 171, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 3] No such process

real    2m18.661s
user    0m3.541s
sys     0m46.695s
```
Suggested fix:
```
diff --git a/dispatcher.py b/dispatcher.py
index 9f9c044..61e46af 100644
--- a/dispatcher.py
+++ b/dispatcher.py
@@ -112,7 +112,10 @@ class Dispatcher:
     def terminate_all_workers(self):
         for process in self.processes:
             if process.is_alive():
-                process.terminate()
+                try:
+                    process.terminate()
+                except OSError:
+                    pass
 
     def kill_all_workers(self):
         for pid in self.pids:
```

**Comment by Totktonada** [comment]
Similar to d56203109f5d496cc77c7249cd79126541b70123.

**Comment by Totktonada** [comment]
Hm. Things are more tricky for `multiprocessing.Process` (see file `/usr/lib/python2.7/multiprocessing/forking.py`):

```python
        def terminate(self):
            if self.returncode is None:
                try:
                    os.kill(self.pid, signal.SIGTERM)
                except OSError, e:
                    if self.wait(timeout=0.1) is None:
                        raise
```

Not so easy to reproduce as for just Popen handle. However I see what is going on: the process is already terminated, but SIGCHILD is not delivered to the parent process for 0.1 seconds.
