### ISSUE TITLE
TypeError: bad operand type for abs(): 'NoneType'

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/test-run#28]
```
---------------------------------------------------------------------------
box-py/args.test.py                                             Traceback (most recent call last):
  File "/home/travis/build/rtsisyk/tarantool/test-run/lib/test.py", line 120, in run
    self.execute(server)
  File "/home/travis/build/rtsisyk/tarantool/test-run/lib/tarantool_server.py", line 124, in execute
    server.crash_grep()
  File "/home/travis/build/rtsisyk/tarantool/test-run/lib/tarantool_server.py", line 567, in crash_grep
    sys.stdout.write('[Signal=%d]\n' % abs(self.process.returncode))
TypeError: bad operand type for abs(): 'NoneType'
[ fail ]
Test failed! Last 10 lines of the result file:

tarantool -V
Tarantool 1.minor.patch-<rev>-<commit>
Target: platform <build>
Build options: flags
Compiler: cc
C_FLAGS: flags
CXX_FLAGS: flags

[Instance "box" crash detected]
```

[travis-log.txt](https://github.com/tarantool/test-run/files/266266/travis-log.txt)

**Comment by rtsisyk** [comment]
I also wonder what is "Tarantool 1.minor.patch-<rev>-<commit>"
