### ISSUE TITLE
OSError: [Errno 24] Too many open files on OS X

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/test-run#31]
```
Starting the server ...

Starting /Users/travis/build/tarantool/tarantool/test/var/vinyl.lua 

Traceback (most recent call last):

  File "test-run.py", line 235, in <module>

    exit(main())

  File "test-run.py", line 213, in main

    failed_tests.extend(suite.run_all())

  File "/Users/travis/build/tarantool/tarantool/test-run/lib/test_suite.py", line 121, in run_all

    self.server.deploy(silent=False)

  File "/Users/travis/build/tarantool/tarantool/test-run/lib/tarantool_server.py", line 519, in deploy

    self.start(silent=silent, **kwargs)

  File "/Users/travis/build/tarantool/tarantool/test-run/lib/tarantool_server.py", line 556, in start

    color_stdout(self.version() + "\n", schema='version')

  File "/Users/travis/build/tarantool/tarantool/test-run/lib/tarantool_server.py", line 789, in version

    stdout = subprocess.PIPE)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 703, in __init__

    errread, errwrite) = self._get_handles(stdin, stdout, stderr)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1110, in _get_handles

    c2pread, c2pwrite = self.pipe_cloexec()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1153, in pipe_cloexec

    r, w = os.pipe()

OSError: [Errno 24] Too many open files

[INFO/MainProcess] process shutting down

make: *** [travis_test_osx] Error 1
```

https://travis-ci.org/tarantool/tarantool/jobs/156346550

**Comment by rtsisyk** [comment]
This problem has been fixed on Travis CI.
