### ISSUE TITLE
Latest test-run update fails tarantool-ee tests

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/test-run#442]
After bumping test-run to commit b8b60b409126887b4efe7a95a55e022af69bd544 tarantool-ee tests start failing like this
[example in tarantool-ee CI](https://github.com/tarantool/tarantool-ee/actions/runs/10064680520/job/27822117830?pr=839):
```
No output during 10 seconds. Will abort after 320 seconds without output. List of workers not reporting the status:
- 091_etcd-client [etcd-client/etcd_client_general_integration_test.lua, None] at /tmp/t/091_etcd-client/etcd_client_general_integration.result:507
No output during 20 seconds. Will abort after 320 seconds without output. List of workers not reporting the status:
- 091_etcd-client [etcd-client/etcd_client_general_integration_test.lua, None] at /tmp/t/091_etcd-client/etcd_client_general_integration.result:1003
No output during 30 seconds. Will abort after 320 seconds without output. List of workers not reporting the status:
Traceback (most recent call last):
  File "/__w/tarantool-ee/tarantool-ee/tarantool/test/./test-run.py", line 344, in <module>
    status = main_parallel()
  File "/__w/tarantool-ee/tarantool-ee/tarantool/test/./test-run.py", line 158, in main_parallel
    res = main_loop_parallel()
  File "/__w/tarantool-ee/tarantool-ee/tarantool/test/./test-run.py", line 129, in main_loop_parallel
    dispatcher.wait()
  File "/__w/tarantool-ee/tarantool-ee/tarantool/test-run/dispatcher.py", line 270, in wait
    objs = self.invoke_listeners(inputs, ready_inputs)
  File "/__w/tarantool-ee/tarantool-ee/tarantool/test-run/dispatcher.py", line 288, in invoke_listeners
    listener.process_timeout(self.report_timeout)
  File "/__w/tarantool-ee/tarantool-ee/tarantool/test-run/listeners.py", line 463, in process_timeout
    lines = sum(1 for _ in f)
  File "/__w/tarantool-ee/tarantool-ee/tarantool/test-run/listeners.py", line 463, in <genexpr>
    lines = sum(1 for _ in f)
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 5027: invalid start byte
```

**Comment by sergepetrenko** [comment]
Applying the following patch seems to fix the issue:
```diff
diff --git a/listeners.py b/listeners.py
index bba9578..11c5601 100644
--- a/listeners.py
+++ b/listeners.py
@@ -459,7 +459,7 @@ class HangWatcher(BaseWatcher):
             result_file = task.task_tmp_result
             result_file_summary = '(no result file {})'.format(result_file)
             if os.path.exists(result_file):
-                with open(result_file, 'r') as f:
+                with open(result_file, 'r', encoding='utf-8', errors='replace') as f:
                     lines = sum(1 for _ in f)
                     result_file_summary = 'at {}:{}'.format(result_file,
                                                             lines)
```

**Comment by sergepetrenko** [comment]
Speaking of `subscribe_once` tests failure, the `subscribe/once_test.lua`, has 4 test cases which influence `test_create_with_concurrent_close`:
 * `unit.subscribe.once.test_read_error_closes`
 * `unit.subscribe.once.test_read_no_result_closes`
 * `unit.subscribe.once.test_read_invalid_format_closes`
 * `unit.subscribe.once.test_create_multiple_with_timeout`

Commenting them all out or putting the `test_create_with_concurrent_close` before them stops the failure, which's quite suspicious. I don't see any reason for the tests to start influencing each other due to test-run (luatest) update.

**Comment by sergepetrenko** [comment]
> Speaking of `subscribe_once` tests failure, the `subscribe/once_test.lua`, has 4 test cases which influence `test_create_with_concurrent_close`:
> 
> * `unit.subscribe.once.test_read_error_closes`
> * `unit.subscribe.once.test_read_no_result_closes`
> * `unit.subscribe.once.test_read_invalid_format_closes`
> * `unit.subscribe.once.test_create_multiple_with_timeout`
> 
> Commenting them all out or putting the `test_create_with_concurrent_close` before them stops the failure, which's quite suspicious. I don't see any reason for the tests to start influencing each other due to test-run (luatest) update.

Also this diff fixes the `subscribe_once` test:
```diff
diff --git a/test/unit/subscribe/once_test.lua b/test/unit/subscribe/once_test.lua
index e401d77..b6bab85 100644
--- a/test/unit/subscribe/once_test.lua
+++ b/test/unit/subscribe/once_test.lua
@@ -236,6 +236,7 @@ g.test_create_with_concurrent_close = function()
     t.assert(c2:status(), "dead")
     fiber.yield()
     t.assert_equals(before_read, 1)
+    fiber.yield()
     t.assert_equals(after_read, 1)
 end
      
```
