### ISSUE TITLE
ImportError: No module named platform

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/test-run#48]
```
./test-run.py

[CUT]

================================================================================
TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------
replication/autobootstrap.test.lua              memtx           [ pass ]
replication/autobootstrap_guest.test.lua        memtx           [ pass ]
replication/catch.test.lua                      memtx           [ pass ]
replication/consistent.test.lua                 memtx           [ disabled ]
replication/errinj.test.lua                     memtx           [ pass ]
replication/hot_standby.test.lua                memtx           Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/threadpool.py", line 289, in _on_async
  File "/Library/Python/2.7/site-packages/gevent/event.py", line 380, in __call__
  File "/Library/Python/2.7/site-packages/gevent/event.py", line 246, in set_exception
  File "/Library/Python/2.7/site-packages/gevent/_tblib.py", line 243, in g
  File "/Library/Python/2.7/site-packages/gevent/_tblib.py", line 297, in dump_traceback
  File "/Library/Python/2.7/site-packages/gevent/_tblib.py", line 274, in _init
ImportError: No module named platform
<async at 0x10600d980> failed with ImportError

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/threadpool.py", line 289, in _on_async
  File "/Library/Python/2.7/site-packages/gevent/event.py", line 380, in __call__
  File "/Library/Python/2.7/site-packages/gevent/event.py", line 246, in set_exception
  File "/Library/Python/2.7/site-packages/gevent/_tblib.py", line 243, in g
  File "/Library/Python/2.7/site-packages/gevent/_tblib.py", line 298, in dump_traceback
TypeError: 'NoneType' object is not callable
<async at 0x10600d520> failed with TypeError

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/baseserver.py", line 175, in _do_read
  File "/Library/Python/2.7/site-packages/gevent/server.py", line 114, in do_read
  File "/Library/Python/2.7/site-packages/gevent/_socket2.py", line 161, in accept
error: [Errno 24] Too many open files
<TarantoolInspector at 0x10562bf10 fileno=116 address=127.0.0.1:50676> failed with error

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/baseserver.py", line 175, in _do_read
  File "/Library/Python/2.7/site-packages/gevent/server.py", line 114, in do_read
  File "/Library/Python/2.7/site-packages/gevent/_socket2.py", line 161, in accept
error: [Errno 24] Too many open files
<TarantoolInspector at 0x10562bf10 fileno=116 address=127.0.0.1:50676> failed with error
```

100% reproducibility on tt-mac.

```
python
Python 2.7.11 (default, Feb  4 2016, 18:52:50)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
>>> gevent.__version__
'1.1b5'
>>>
```

**Comment by rtsisyk** [comment]
ImportError is caused by "Too many open files".
I still wonder why test-run uses so many sockets.
