### ISSUE TITLE
Support more then 60 parallel jobs

### ISSUE THREAD

**Issue by Totktonada** [tarantool/test-run#82]
How to reproduce:

```
./test-run.py -j 61
```

Expected: 60 workers created, 1 pending.

Got:

```
Traceback (most recent call last):
  File "./test-run.py", line 211, in <module>
    status = main_parallel()
  File "./test-run.py", line 137, in main_parallel
    res = main_loop_parallel()
  File "./test-run.py", line 98, in main_loop_parallel
    dispatcher.start()
  File "/home/alex/projects/tarantool-meta/1.7/tarantool/test-run/dispatcher.py", line 151, in start
    self.run_max_workers()
  File "/home/alex/projects/tarantool-meta/1.7/tarantool/test-run/dispatcher.py", line 147, in run_max_workers
    ok = self.add_worker()
  File "/home/alex/projects/tarantool-meta/1.7/tarantool/test-run/dispatcher.py", line 195, in add_worker
    self.worker_next_id)
  File "/home/alex/projects/tarantool-meta/1.7/tarantool/test-run/dispatcher.py", line 35, in acquire_range
    tcp_port_range = self.available_ranges.pop()
KeyError: 'pop from an empty set'
```

**Comment by Totktonada** [comment]
Alternatively we can scale a port range size depending on max workers count.
